SELECT COUNT(DISTINCT(C_CUSTKEY)) FROM CUSTOMER
WHERE C_CUSTKEY NOT IN(
    SELECT C_CUSTKEY FROM CUSTOMER
    INNER JOIN ORDERS ON O_CUSTKEY = C_CUSTKEY
    WHERE O_COMMENT LIKE '%special request%');